baseURL = 'https://rwklibrary.com/'
languageCode = 'en-us'
title = 'Rhys Wesley King'
theme = "hugo-theme-console"

[params]
  description = "Hello World"
  animateStyle = "animated flash"
  titleCutting = false

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Blog"
  url = "/blog/"

[[params.navlinks]]
  name = "Portfolio"
  url = "/portfolio/"

[[params.navlinks]]
  name = "Shop"
  url = "/shop/"

[[params.navlinks]]
  name = "Links"
  url = "/links/"

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = true