baseURL = 'https://rhyswesleyking.cc/'
languageCode = 'en-us'
title = 'Rhys Wesley King'
theme = "hugo-theme-console"

[params]
  description = "test"
  animateStyle = "animate-fade-up"

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Blog"
  url = "/blog/"

[[params.navlinks]]
  name = "Portfolio"
  url = "/portfolio/"

[[params.navlinks]]
  name = "Shop"
  url = "/shop/"

[[params.navlinks]]
  name = "links"
  url = "/links/"